name: crazybattle
version: "2.0"
summary: Crazy Battle
description: |
  submission for Linux Game Jam 2018.

confinement: devmode

apps:
  crazybattle:
    command: usr/bin/crazybattle/CrazyBattle

parts:
  crazybattle:
    plugin: cmake
    source: .
    build-packages:
      - g++
      - make
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsdl2-image-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libsdl2-image-2.0-0
      - libpulse0
